title: ResStock
description: ResStock Documentation
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
url: https://github.com/NREL/ResStock.github.io
logo: "/assets/images/logo.svg"
markdown: kramdown
kramdown:
  math_engine: mathjax
favicon_ico: "/assets/images/favicon.ico"
search_enabled: true
aux_links:
  "ResStock on GitHub":
    - "https://github.com/NREL/resstock"
aux_links_new_tab: true
footer_content: >
  The National Laboratory of the Rockies is a national laboratory of the
  <a href="https://www.energy.gov">U.S. Department of Energy</a>,
  <a href="https://www.energy.gov/eere/office-energy-efficiency-and-renewable-energy?nrg_redirect=467275">Office of Critical Minerals and Energy Innovation</a>,
  operated under Contract No. DE-AC36-08GO28308
color_scheme: general
callouts:
  warning:
    title: Warning
    color: red
  publication:
    color: blue
    opacity: 0.1
  relatedwork:
    color: yellow
    opacity: 0.1
  othermedia:
    color: grey-dk
    opacity: 0.1

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-5WNQG7LNVD
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

